version: '3'

services:
    nginx:
        build:
            context: ./_nginx
        volumes:
            - ./src:/var/www
            - ./_nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./_nginx/sites/:/etc/nginx/sites-available
            - ./_nginx/conf.d/:/etc/nginx/conf.d
        depends_on:
            - php-fpm
        ports:
            - "80:80"
            - "443:443"
    php-fpm:
        build:
            context: ./php-fpm
        volumes:
            - ./src:/var/www
    # database:
    #     build:
    #         context: ./database
    #     environment:
    #         - MYSQL_DATABASE=mydb
    #         - MYSQL_USER=phpuser
    #         - MYSQL_PASSWORD=sdrugntqqsciur
    #         - MYSQL_ROOT_PASSWORD=docker
    #     volumes:
    #         - ./database/data.sql:/docker-entrypoint-initdb.d/data.sql
            

